const MESSAGE = {
  REGISTER_SUCCESSFULLY: "Registration Successfully",
  USER_ERROR: "Registration failed",
  LOGIN_SUCCESS: "login Successfully",
  LOGIN_ERROR: "Email does not exist",
  PROFILE: "Here your profile",
  PROFILE_UPDATED: "Profile updated Successfully",
  EMAIl_ERROR: "Email already exist",
  INVALID_CREDENTIALS: "Invalid credentials",
  USER_NOT_EXIST: "User not exist",
  SERVER_ERROR: "Something went wrong please try again",
  USER_RECORD_DELETED: "Record Deleted ",
  USER_NOT_FOUND: "User not found",
  PASSWORD_ERROR: "Using wrong password",
  DELETE_ERROR: "NOT DELETE",
  RECORD_NOT: "Record not found",
  VALIDATION_ERROR: "Not Valid",
  IMAGE_UPLOAD_SUCCESSFULLY: "Image uploaded successfully",
  IMAGE_UPLOAD_FAILED: "Image upload failed",
  QUOTE_ADD_SUCCESSFULLY: "Quote added successfully",
  QUOTE_RECORD: "Here Your Quote Record",
};
export default MESSAGE;
